---
name: Bulid and Deploy React App to GitHub pages
on:
  push:
    branches: [main]
jobs:
  bulid-and-deploy:
    name: Bulid and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        user: actions/Checkout@v2

      - name: Bulid
        run: yarn install

      - name: Test
        run: yarn run test

      - name: Deploy
        run: |
          git config --global user.name 'Amos Ahounou'
          git config --global user.email 'amosahounou10@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy
